# Generated by Django 5.0.7 on 2024-08-23 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.AddField(
            model_name='genre',
            name='Desc',
            field=models.CharField(default='No Description', max_length=300),
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('file', models.FileField(null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=models.SET('Unknown Author'), to='base.author')),
                ('creator', models.ForeignKey(on_delete=models.SET('Unknown Creator'), related_name='created_travels', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(blank=True, related_name='travels', to='base.genre')),
            ],
            options={
                'ordering': ['name', 'created'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.travel'),
        ),
        migrations.AddField(
            model_name='user',
            name='travels',
            field=models.ManyToManyField(blank=True, related_name='users', to='base.travel'),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
